RecycleBitBackEnd/Controllers/LogFileController.cs
using HarpiaCommon.Config;
using HarpiaCommon.Exceptions;
using HarpiaCommon.Models.Request;
using HarpiaCommon.Services.Interfaces;
using RecycleBitBackEnd.Util;
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Web.Mvc;

namespace RecycleBitBackEnd.Controllers {

    /// <summary>
    ///
    /// </summary>
    public class LogsFilesController : Controller {
        private readonly IHarpiaLoggerBO loggerBO;

        public LogsFilesController() {
        }

        public LogsFilesController(IHarpiaLoggerBO loggerBO) {
            this.loggerBO = loggerBO ?? throw new ArgumentNullException("loggerBO");
        }

        /// <summary>
        ///     Method responsable per process action.
        /// </summary>
        /// <returns>
        ///     View API
        /// </returns>
        public ActionResult LogsFiles() {
            DirectoryInfo directoryInfo = new DirectoryInfo(CommonConfig.FileNLogPath);
            if (directoryInfo.Exists) {
                List<FileInfo> Files = directoryInfo.GetFiles("*.log").ToList().OrderByDescending(order => order.LastWriteTime).ToList();
                ViewBag.logList = Files;
            } else {
                ViewBag.logList = new List<FileInfo>();
            }
            return View();
        }

        /// <summary>
        ///
        /// </summary>
        /// <param name="fileFullName"></param>
        /// <returns></returns>
        /// <summary>
        ///     Method responsable per download file zip
        /// </summary>
        /// <param name="fileFullName"></param>
        /// <returns></returns>
        public FileStreamResult DownloadFile(string fileFullName) {
            try {
                string physicalPath = Path.Combine(CommonConfig.FileNLogPath, fileFullName.EndsWith(".log") ? fileFullName : fileFullName + ".log");

                string zipPath = Path.Combine(CommonConfig.FileNLogPath, fileFullName.Replace(".log", ".zip"));

                if (System.IO.File.Exists(zipPath)) {
                    System.IO.File.Delete(zipPath);
                }

                using (ZipArchive archive = ZipFile.Open(zipPath, ZipArchiveMode.Create)) {
                    archive.CreateEntryFromFile(physicalPath, fileFullName);
                }

                byte[] fileBytes = System.IO.File.ReadAllBytes(zipPath);
                MemoryStream ms = new MemoryStream(fileBytes);
                return new FileStreamResult(ms, "application/zip") { FileDownloadName = zipPath };
            } catch (UtilException exception) {
                loggerBO.SetErrorLog(new NewLogErrorRequest((string)ApplicationParameters.Params.ApplicationName, DateTime.Now, exception.Message, string.Empty, this.GetMethodContext(), exception, exception.StackTrace));
            } catch (ProjectException exception) {
                loggerBO.SetErrorLog(new NewLogErrorRequest((string)ApplicationParameters.Params.ApplicationName, DateTime.Now, exception.Message, string.Empty, this.GetMethodContext(), exception, exception.StackTrace));
            } catch (Exception exception) {
                loggerBO.SetErrorLog(new NewLogErrorRequest((string)ApplicationParameters.Params.ApplicationName, DateTime.Now, exception.Message, string.Empty, this.GetMethodContext(), exception, exception.StackTrace));
            }
            return null;
        }
    }
}

RecycleBitBackEnd/Controllers/LogsZipController.cs
using HarpiaCommon.Config;
using HarpiaCommon.Exceptions;
using HarpiaCommon.Models.Request;
using HarpiaCommon.Services.Interfaces;
using RecycleBitBackEnd.Util;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace RecycleBitBackEnd.Controllers {

    public class LogsZipController : Controller {
        private readonly IHarpiaLoggerBO loggerBO;

        public LogsZipController() {
        }

        public LogsZipController(IHarpiaLoggerBO loggerBO) {
            this.loggerBO = loggerBO ?? throw new ArgumentNullException("loggerBO");
        }

        /// <summary>
        ///     Method responsable per process action.
        /// </summary>
        /// <returns>
        ///     View API
        /// </returns>
        public ActionResult LogsZip() {
            try {
                DirectoryInfo directoryInfo = new DirectoryInfo(CommonConfig.FileNLogPath);
                if (directoryInfo.Exists) {
                    List<FileInfo> Files = directoryInfo.GetFiles("*.zip").ToList().OrderByDescending(order => order.LastWriteTime).ToList();
                    ViewBag.logList = Files;
                } else {
                    ViewBag.logList = new List<FileInfo>();
                }
            } catch (UtilException exception) {
                loggerBO.SetErrorLog(new NewLogErrorRequest((string)ApplicationParameters.Params.ApplicationName, DateTime.Now, exception.Message, string.Empty, this.GetMethodContext(), exception, exception.StackTrace));
            } catch (ProjectException exception) {
                loggerBO.SetErrorLog(new NewLogErrorRequest((string)ApplicationParameters.Params.ApplicationName, DateTime.Now, exception.Message, string.Empty, this.GetMethodContext(), exception, exception.StackTrace));
            } catch (Exception exception) {
                loggerBO.SetErrorLog(new NewLogErrorRequest((string)ApplicationParameters.Params.ApplicationName, DateTime.Now, exception.Message, string.Empty, this.GetMethodContext(), exception, exception.StackTrace));
            }
            return View();
        }

        public FileStreamResult DownloadFile(string fileFullName) {
            try {
                string physicalPath = Path.Combine(CommonConfig.FileNLogPath, fileFullName.EndsWith(".zip") ? fileFullName : fileFullName + ".zip");
                string physicalPathCopy = Path.Combine(CommonConfig.FileNLogPath, fileFullName.EndsWith(".zip") ? fileFullName.Replace(".zip", DateTime.Now.Millisecond.ToString() + ".zip") : fileFullName + DateTime.Now.Millisecond.ToString() + ".zip");
                System.IO.File.Copy(physicalPath, physicalPathCopy);
                byte[] fileBytes = System.IO.File.ReadAllBytes(physicalPathCopy);
                MemoryStream ms = new MemoryStream(fileBytes);
                System.IO.File.Delete(physicalPathCopy);
                return new FileStreamResult(ms, "application/zip") { FileDownloadName = fileFullName };
            } catch (UtilException exception) {
                loggerBO.SetErrorLog(new NewLogErrorRequest((string)ApplicationParameters.Params.ApplicationName, DateTime.Now, exception.Message, string.Empty, this.GetMethodContext(), exception, exception.StackTrace));
            } catch (ProjectException exception) {
                loggerBO.SetErrorLog(new NewLogErrorRequest((string)ApplicationParameters.Params.ApplicationName, DateTime.Now, exception.Message, string.Empty, this.GetMethodContext(), exception, exception.StackTrace));
            } catch (Exception exception) {
                loggerBO.SetErrorLog(new NewLogErrorRequest((string)ApplicationParameters.Params.ApplicationName, DateTime.Now, exception.Message, string.Empty, this.GetMethodContext(), exception, exception.StackTrace));
            }
            return null;
        }
    }
}

RecycleBitBackEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<html lang="pt-br">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("RecycleBitBackEnd","Index","Home",new { area = "" },new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">@Html.ActionLink("Página Inicial","Index","Home",new { area = "" },new { @class = "nav-link" })</li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropLogs" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Logs
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                            <li class="nav-item">@Html.ActionLink("Logs","Logs","Logs",new { area = "" },new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("Logs Files","LogsFiles","LogsFiles",new { area = "" },new { @class = "nav-link" })</li>
                            <li class="nav-item">@Html.ActionLink("Logs Zip","LogsZip","LogsZip",new { area = "" },new { @class = "nav-link" })</li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropJobs" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Jobs
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                            <li class="nav-item">@Html.ActionLink("Job Executions","JobExecution","JobExecution",new { area = "" },new { @class = "nav-link" })</li>
                            <!--<li class="nav-item">@Html.ActionLink("Jobs Manager","JobExecution","JobExecution",new { area = "" },new { @class = "nav-link" })</li> -->
                            <li class="nav-item">@Html.ActionLink("Job Schedules","JobScheduleInfo","JobScheduleInfo",new { area = "" },new { @class = "nav-link" })</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - RecycleBitBackEnd</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts",required: false)
</body>
</html>